# Generated by Django 2.1 on 2018-08-28 04:31

from django.db import migrations, models
import objectdash.web.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleAnnotation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.TextField()),
                ('xmin', models.IntegerField()),
                ('xmax', models.IntegerField()),
                ('ymin', models.IntegerField()),
                ('ymax', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ExampleImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_file', models.ImageField(upload_to=objectdash.web.models.example_image_upload_to)),
                ('source', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PBObjectDetector',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('pb_file', models.FileField(help_text='frozen_inference_graph.pb', upload_to=objectdash.web.models.object_detector_upload_to)),
                ('label_file', models.FileField(help_text='labels.pbtxt', upload_to=objectdash.web.models.object_detector_upload_to)),
                ('num_classes', models.IntegerField(default=90)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Object Detector',
                'verbose_name_plural': 'Object Detectors',
            },
        ),
        migrations.AddField(
            model_name='exampleannotation',
            name='example_image',
            field=models.ForeignKey(on_delete='cascade', related_name='annotations', to='web.ExampleImage'),
        ),
    ]
