# Generated by Django 2.1 on 2018-08-29 06:19

from django.db import migrations, models
import django.db.models.deletion
import objectdash.web.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotatedImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_file', models.ImageField(height_field='height', upload_to=objectdash.web.models.example_image_upload_to, width_field='width')),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('source', models.TextField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('xmin', models.IntegerField()),
                ('xmax', models.IntegerField()),
                ('ymin', models.IntegerField()),
                ('ymax', models.IntegerField()),
                ('example_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='web.AnnotatedImage')),
            ],
            options={
                'verbose_name': 'Annotation',
                'verbose_name_plural': 'Annotations',
            },
        ),
        migrations.CreateModel(
            name='AnnotationLabel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.TextField()),
            ],
            options={
                'verbose_name': 'Annotation Label',
                'verbose_name_plural': 'Annotation Labels',
            },
        ),
        migrations.CreateModel(
            name='ObjectDetector',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('pb_file', models.FileField(help_text='frozen_inference_graph.pb', upload_to=objectdash.web.models.object_detector_upload_to)),
                ('label_file', models.FileField(help_text='labels.pbtxt', upload_to=objectdash.web.models.object_detector_upload_to)),
                ('num_classes', models.IntegerField(default=90)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Object Detector',
                'verbose_name_plural': 'Object Detectors',
            },
        ),
        migrations.CreateModel(
            name='TFRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tf_record_file', models.FileField(upload_to=objectdash.web.models.tf_record_file_upload_to)),
                ('annotation_labels', models.ManyToManyField(to='web.AnnotationLabel')),
            ],
            options={
                'verbose_name': 'Tensorflow Record',
                'verbose_name_plural': 'Tensorflow Records',
            },
        ),
        migrations.AddField(
            model_name='annotation',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.AnnotationLabel'),
        ),
    ]
