# Generated by Django 2.1 on 2018-08-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbobjectdetector',
            name='num_classes',
            field=models.IntegerField(default=90),
        ),
    ]
